# Generated by Django 5.2.10 on 2026-02-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('retailer', models.CharField(blank=True, max_length=100)),
                ('segment', models.CharField(blank=True, choices=[('FIRST_PARTY', 'First Party'), ('THIRD_PARTY', 'Third Party')], max_length=32, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'sku', 'country'), name='uniq_merchant_sku_country')],
            },
        ),
    ]
