# Generated by Django 5.2.10 on 2026-02-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_annotater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailrow',
            name='country',
            field=models.CharField(max_length=3),
        ),
    ]
